package com.xbrother.common.entity.rights;

// Generated 2013-7-22 15:04:22 by Hibernate Tools 4.0.0

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.xbrother.common.constants.DatabaseConst;
import com.xbrother.common.entity.BaseEntity;

/**
 * Facter generated by hbm2java
 */
@Entity
@Table(name = "ajx_facter", catalog = DatabaseConst.CATALOG)
public class Facter extends BaseEntity{

	private String facterName;
	private String facterValue;
	private Set<Permission> permissions;


	@Column(name = "facter_name", nullable = false, length = 128)
	public String getFacterName() {
		return this.facterName;
	}

	public void setFacterName(String facterName) {
		this.facterName = facterName;
	}

	@Column(name = "facter_value", nullable = false, length = 128)
	public String getFacterValue() {
		return this.facterValue;
	}

	public void setFacterValue(String facterValue) {
		this.facterValue = facterValue;
	}

	@OneToMany(cascade=CascadeType.ALL,mappedBy="facter")
	public Set<Permission> getPermissions() {
		return permissions;
	}

	public void setPermissions(Set<Permission> permissions) {
		this.permissions = permissions;
	}

}
