package com.xbrother.common.entity.rights;

// Generated 2013-7-22 15:04:22 by Hibernate Tools 4.0.0

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.xbrother.common.constants.DatabaseConst;
import com.xbrother.common.entity.BaseEntity;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "ajx_permission", catalog = DatabaseConst.CATALOG)
public class Permission extends BaseEntity {

	private Facter facter;
	private String actionType;
	private String description;
	private Set<RolePermission> rolePermissions;
	private Set<Menu> menus;

	@Column(name = "action_type", nullable = false, length = 64)
	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "permission")
	public Set<RolePermission> getRolePermissions() {
		return rolePermissions;
	}

	public void setRolePermissions(Set<RolePermission> rolePermissions) {
		this.rolePermissions = rolePermissions;
	}

	@ManyToOne
	@JoinColumn(name = "facter_id", nullable = false)
	public Facter getFacter() {
		return facter;
	}

	public void setFacter(Facter facter) {
		this.facter = facter;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "permission")
	public Set<Menu> getMenus() {
		return menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

}
