package com.xbrother.common.entity.rights;

// Generated 2013-7-22 15:04:22 by Hibernate Tools 4.0.0

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.xbrother.common.constants.DatabaseConst;
import com.xbrother.common.entity.BaseEntity;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "ajx_role", catalog = DatabaseConst.CATALOG)
public class Role extends BaseEntity {

	private String roleName;
	private String description;
	private Set<RolePermission> rolePermissions;
	private Set<UserRole> userRoles;


	@Column(name = "role_name", nullable = false, length = 128)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "role")
	public Set<RolePermission> getRolePermissions() {
		return rolePermissions;
	}

	public void setRolePermissions(Set<RolePermission> rolePermissions) {
		this.rolePermissions = rolePermissions;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "role")
	public Set<UserRole> getUserRoles() {
		return userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

}
