package com.xbrother.common.entity.rights;

// Generated 2013-7-22 15:04:22 by Hibernate Tools 4.0.0

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.xbrother.common.constants.DatabaseConst;
import com.xbrother.common.entity.IdEntity;

/**
 * RolePermission generated by hbm2java
 */
@Entity
@Table(name = "ajx_role_permission", catalog = DatabaseConst.CATALOG)
public class RolePermission extends IdEntity{

	private Role role;
	private Permission permission;

	@ManyToOne()
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne
	@JoinColumn(name = "permission_id", nullable = false)
	public Permission getPermission() {
		return permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

}
